version: '3'
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: brewery
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "6033:3306"
  brewery-app:
    restart: on-failure
    build: ./
    expose:
      - "8080"
    ports:
      - 8080:8080
    depends_on:
      - docker-mysql
