version: "3"
services:
  brewery:
    image: brewery
    restart: on-failure
    ports:
    - "8080:8080"
    depends_on:
      - database

  database:
    image: mysql:latest
    restart: always
    ports:
    - "6033:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=brewery
